### ISSUE TITLE
Add Apache 2.0 license file to root folder.

### ISSUE THREAD

**Issue by garydgregory** [edwgiz-zz/maven-shaded-log4j-transformer#2]
Hello,

Would you mind licensing this code as Apache 2.0?

You can add the Apache 2.0 license file to root folder? 

Here is a link to one: https://svn.apache.org/repos/asf/commons/proper/bcel/tags/BCEL_6_0_RC6/LICENSE.txt

Thank you,
Gary

**Comment by edwgiz-zz** [comment]
Is ok if the licence will be placed in `src/main/resources/META-INF/LICENSE.txt` ?

**Comment by garydgregory** [comment]
Hi,

By convention, we (at Apache) usually place a LICENCE.txt in the root of the repository. For example: https://git-wip-us.apache.org/repos/asf?p=logging-log4j2.git;a=blob;f=LICENSE.txt;h=6279e5206de1367a1fa0356bafb739d0e9ad0413;hb=HEAD

When the jar file is built, the license ends up in the META-INF folder in the jar.

Would that work for you?

Thank you,
Gary

**Comment by edwgiz-zz** [comment]
Ok, I move it in root soon.

Btw, couldn't you test 2.6.1 plugin version? It's on central.maven.org now.
